In [2]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("Movie.csv")
df

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [8]:
df.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [10]:
df.tail()

      userId             movie  rating
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

In [12]:
df.isnull().sum()

userId    0
movie     0
rating    0
dtype: int64

In [14]:
user_movies_df.index=movie_df.userId.unique()

NameError: name 'movie_df' is not defined